# Generated by Django 3.0.1 on 2020-05-10 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicwall', '0002_auto_20200508_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_content',
            new_name='content',
        ),
    ]
