# Generated by Django 3.0.2 on 2020-03-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicwall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercode',
            name='expires',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usercode',
            name='maxuses',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usercode',
            name='uses',
            field=models.IntegerField(default=0),
        ),
    ]
